# Generated by Django 4.0 on 2022-04-17 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('time', models.TimeField()),
                ('user_who_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stacks', to='habit_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('stacks_part_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacked_habits', to='habit_app.stack')),
            ],
        ),
    ]
