# Generated by Django 4.0.4 on 2022-04-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='stacks_part_of',
            new_name='stack_part_of',
        ),
    ]
