# Generated by Django 4.0.4 on 2022-04-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0002_rename_stacks_part_of_habit_stack_part_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default='Hi! I like TREES!'),
        ),
    ]
